openapi: 3.0.0
info:
  title: TaskMaster Pro API
  version: 1.0.0
  description: API para gestión de tareas, proyectos y equipos con OAuth
  contact:
    email: soporte@taskmasterpro.com

servers:
  - url: https://taskmaster-pro-y6q8.onrender.com/api
    description: Servidor de producción
  - url: http://localhost:3000/api
    description: Servidor local

tags:
  - name: Auth
    description: Autenticación OAuth
  - name: Users
    description: Operaciones con usuarios
  - name: Tasks
    description: Gestión de tareas (requiere autenticación)
  - name: Projects
    description: Gestión de proyectos (requiere autenticación)
  - name: Teams
    description: Gestión de equipos

securitySchemes:
  googleOAuth:
    type: oauth2
    flows:
      authorizationCode:
        authorizationUrl: https://accounts.google.com/o/oauth2/v2/auth
        tokenUrl: https://oauth2.googleapis.com/token
        scopes:
          email: Ver dirección de email
          profile: Ver perfil básico

paths:
  /auth/google:
    get:
      tags: [Auth]
      summary: Iniciar autenticación con Google
      description: Redirige a Google OAuth para autenticación
      responses:
        '302':
          description: Redirección a Google
  /auth/google/callback:
    get:
      tags: [Auth]
      summary: Callback de Google OAuth
      description: Endpoint de retorno después de autenticar en Google
      responses:
        '302':
          description: Redirección a la interfaz
        '401':
          description: Autenticación fallida
  /auth/logout:
    get:
      tags: [Auth]
      summary: Cerrar sesión
      responses:
        '302':
          description: Redirección al inicio

  /users:
    get:
      tags: [Users]
      summary: Obtener todos los usuarios
      responses:
        '200':
          description: Lista de usuarios
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
    post:
      tags: [Users]
      summary: Crear usuario
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '201':
          description: Usuario creado
        '400':
          description: Validación fallida

  /users/{id}:
    get:
      tags: [Users]
      summary: Obtener usuario por ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Usuario encontrado
        '404':
          description: Usuario no encontrado
    put:
      tags: [Users]
      summary: Actualizar usuario
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '200':
          description: Usuario actualizado
        '400':
          description: Validación fallida
    delete:
      tags: [Users]
      summary: Eliminar usuario
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Usuario eliminado

  /tasks:
    get:
      tags: [Tasks]
      summary: Obtener todas las tareas
      security: []
      responses:
        '200':
          description: Lista de tareas
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Task'
    post:
      tags: [Tasks]
      summary: Crear tarea
      security:
        - googleOAuth: [email, profile]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Task'
      responses:
        '201':
          description: Tarea creada
        '400':
          description: Validación fallida
        '401':
          description: No autenticado

  /tasks/{id}:
    get:
      tags: [Tasks]
      summary: Obtener tarea por ID
      security: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Tarea encontrada
        '404':
          description: Tarea no encontrada
    put:
      tags: [Tasks]
      summary: Actualizar tarea
      security:
        - googleOAuth: [email, profile]
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Task'
      responses:
        '200':
          description: Tarea actualizada
        '401':
          description: No autenticado
    delete:
      tags: [Tasks]
      summary: Eliminar tarea
      security:
        - googleOAuth: [email, profile]
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Tarea eliminada

  /projects:
    get:
      tags: [Projects]
      summary: Obtener todos los proyectos
      responses:
        '200':
          description: Lista de proyectos
    post:
      tags: [Projects]
      summary: Crear proyecto
      security:
        - googleOAuth: [email, profile]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Project'
      responses:
        '201':
          description: Proyecto creado
        '400':
          description: Validación fallida

  /projects/{id}:
    get:
      tags: [Projects]
      summary: Obtener proyecto por ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Proyecto encontrado
    put:
      tags: [Projects]
      summary: Actualizar proyecto
      security:
        - googleOAuth: [email, profile]
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Project'
      responses:
        '200':
          description: Proyecto actualizado
    delete:
      tags: [Projects]
      summary: Eliminar proyecto
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Proyecto eliminado

  /teams:
    get:
      tags: [Teams]
      summary: Obtener todos los equipos
      responses:
        '200':
          description: Lista de equipos
    post:
      tags: [Teams]
      summary: Crear equipo
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Team'
      responses:
        '201':
          description: Equipo creado
        '400':
          description: Validación fallida

  /teams/{id}:
    get:
      tags: [Teams]
      summary: Obtener equipo por ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Equipo encontrado
    put:
      tags: [Teams]
      summary: Actualizar equipo
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Team'
      responses:
        '200':
          description: Equipo actualizado
    delete:
      tags: [Teams]
      summary: Eliminar equipo
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Equipo eliminado

components:
  schemas:
    User:
      type: object
      required:
        - googleId
        - name
        - email
      properties:
        googleId:
          type: string
          example: "1234567890"
        name:
          type: string
          example: "Juan Pérez"
        email:
          type: string
          format: email
          example: "juan@example.com"
        avatar:
          type: string
          format: uri
          example: "https://example.com/avatar.jpg"
        role:
          type: string
          enum: [admin, manager, user]
          default: "user"

    Task:
      type: object
      required:
        - title
      properties:
        title:
          type: string
          example: "Implementar OAuth"
        description:
          type: string
          example: "Integrar autenticación con Google"
        status:
          type: string
          enum: [pending, in progress, completed]
          default: "pending"
        priority:
          type: string
          enum: [low, medium, high]
          default: "medium"
        dueDate:
          type: string
          format: date-time
        assignedTo:
          type: string
          format: mongo-id
        projectId:
          type: string
          format: mongo-id

    Project:
      type: object
      required:
        - name
      properties:
        name:
          type: string
          example: "TaskMaster Pro"
        description:
          type: string
          example: "Sistema de gestión de tareas"
        members:
          type: array
          items:
            type: string
            format: mongo-id
        tasks:
          type: array
          items:
            type: string
            format: mongo-id

    Team:
      type: object
      required:
        - name
        - members
      properties:
        name:
          type: string
          example: "Equipo de Desarrollo"
        description:
          type: string
          example: "Equipo principal de desarrollo"
        members:
          type: array
          items:
            type: string
            format: mongo-id
        projects:
          type: array
          items:
            type: string
            format: mongo-id
        leader:
          type: string
          format: mongo-id

  security:
    - googleOAuth: [email, profile]